import { openSans, inter, merriweatherSans, bitter, merriweather, domine, robotoMono, ubuntuMono, ptMono } from "./fonts.js";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }
) {
  return (
    <html lang="en">
      <body className={`
        ${openSans.variable}
        ${inter.variable}
        ${merriweatherSans.variable}
        ${bitter.variable}
        ${merriweather.variable}
        ${domine.variable}
        ${robotoMono.variable}
        ${ubuntuMono.variable}
        ${ptMono.variable}
        bg-darktheme-l1 w-full h-full overflow-hidden
        `}>
        {children}
      </body>
    </html>
  );
}
